### ISSUE TITLE
Nie działające spolszczenie 

### ISSUE THREAD

**Issue by drakolicz1** [dekoza/mtga_polonize#2]
Witam, mam pytanie wczoraj nastąpiła aktualizacja MTG Arena i przestało mi działać spolszczenie, czy do każdej nowej aktualizacji jest potrzebne nowy (przerobiony) instalator spolszczający i jeśli tak to czy będziesz to wypuszczał? pozdrawiam

**Comment by dekoza** [comment]
Problem powinien być już rozwiązany - rozmawialiśmy kilka dni temu :) Póki co zamykam. Jeśli problem znów się pojawi, proszę pisać.
